# Generated by Django 4.2.11 on 2024-03-20 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todaynews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partarticle',
            options={'ordering': ['index']},
        ),
    ]
